apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lanchonete-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/tech-challenge-lanchonete/dev/DB_HOST"
        objectType: "ssmparameter"
        objectAlias: mysqlHost
      - objectName: "/tech-challenge-lanchonete/dev/DB_USERNAME"
        objectType: "ssmparameter"
        objectAlias: mysqlUser
      - objectName: "/tech-challenge-lanchonete/dev/DB_PASSWORD"
        objectType: "ssmparameter"
        objectAlias: mysqlPassword
      - objectName: "/tech-challenge-lanchonete/dev/MAIL_API_URL"
        objectType: "ssmparameter"
        objectAlias: mailtrapApiUrl
      - objectName: "/tech-challenge-lanchonete/dev/MAIL_API_KEY"
        objectType: "ssmparameter"
        objectAlias: mailtrapApiKey
  secretObjects:
    - secretName: lanchonete-secrets-aws
      type: Opaque
      data:
        - objectName: mysqlHost
          key: mysqlHost
        - objectName: mysqlUser
          key: mysqlUser
        - objectName: mysqlPassword
          key: mysqlPassword
        - objectName: mailtrapApiUrl
          key: mailtrapApiUrl
        - objectName: mailtrapApiKey
          key: mailtrapApiKey
